name: Azure Static Web Apps CI/CD
on:
  push:
    branches:
      - main
env:
  APP_LOCATION: "/"
  OUTPUT_LOCATION: "dist/yt-clip-repeater/browser"
permissions:
  issues: write
  contents: read
  pull-requests: write
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4.1.4
      - name: Build And Deploy
        id: builddeploy
        env:
          NODE_VERSION: "18.14.0"
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN  }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          app_build_command: "npm run build"
          output_location: ${{ env.OUTPUT_LOCATION }}
